### ISSUE TITLE
About automatic evaluation

### ISSUE THREAD

**Issue by youriko100** [wangjs9/CARE-master#1]
Hello. I am a NLP beginner. Your work is so nice and I am interested in it. But I have a question about automatic evaluation.
In your paper, BERTScore is also used to evaluate the model, but I can't find the relevant code in Github. Could you please tell me how you do BERTScore in detail? 
Thank you very much!

**Comment by wangjs9** [comment]
I seperate the BertScore Evaluation and the program. And I provide the code I use to evaluate the model in the paper A.1. Hope this can help you!
